version: '3'

services:
  docs:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./docs:/usr/src/app/docs
      - ./sync_tool:/usr/src/app/sync_tool
      - ./README.md:/usr/src/app/README.md
    ports:
      - "5500:5500"
    command: python docs/docs_livereload.py

  tests:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./sync_tool:/usr/src/app/sync_tool
      - ./tests:/usr/src/app/tests
      - ./README.md:/usr/src/app/README.md
      - ./.coveragerc:/usr/src/app/.coveragerc
      - ./pytest.ini:/usr/src/app/pytest.ini
      - ./setup.json:/usr/src/app/setup.json
    command: pytest-watch -n -p
